---
- name: Build Duplicati Github Release URL
  set_fact:
    duplicati_github_url: '{{ github_api_url }}/{{ duplicati_github_repo }}/releases'

- name: Set Release Distribution (Debian)
  set_fact:
    duplicati_release_distro: 'deb'
  when: ansible_os_family | lower == 'debian'

- name: Set Release Distribution (Redhat)
  set_fact:
    duplicati_release_distro: 'rpm'
  when: ansible_os_family | lower == 'redhat'

- name: Find Duplicati Release (Latest Release)
  tags: ["skip_ansible_lint"]
  shell: curl -s '{{ duplicati_github_url }}' | grep browser_download_url | grep '{{ duplicati_release_distro }}' | head -1 | cut -d \" -f 4
  register: duplicati_release
  when: duplicati_release_version | lower == 'latest'

- name: Find Duplicati Release (Specific Release)
  tags: ["skip_ansible_lint"]
  shell: curl -s '{{ duplicati_github_url }}' | grep browser_download_url | grep '{{ duplicati_release_distro }}' | grep '{{ duplicati_release_version }}' | head -1 | cut -d \" -f 4
  register: duplicati_release
  when: not duplicati_release_version | lower == 'latest'

- name: Download and Install Duplicati Release (Debian)
  become: true
  apt:
    deb: '{{ duplicati_release }}'
    state: present
  when: ansible_os_family | lower == 'debian'

- name: Download and Install Duplicati Release (Redhat)
  become: true
  yum:
    name: '{{ duplicati_release }}'
    state: present
  when: ansible_os_family | lower == 'redhat'
