---
- name: Import Find Release Tasks
  tags: ["install-duplicati"]
  import_tasks:
    file: find_release.yml

- name: Import Install Tasks
  tags: ["install-duplicati"]
  import_tasks:
    file: install.yml

- name: Import Service Tasks
  tags: ["install-duplicati", "install-duplicati-service"]
  import_tasks:
    file: service.yml
