---
- name: Include Duplicati Service Option Definitions
  include_vars:
    file: service-option-definitions.yml

- name: Set Duplicati Base Cmd
  set_fact:
    duplicati_execstart_cmd: '{{ duplicati_base_cmd }}'

- name: Add Duplicati Web Port (If Configured)
  set_fact:
    duplicati_execstart_cmd: '{{ duplicati_execstart_cmd + ' ' + duplicati_webservice_port }}'
  when: duplicati_web_port is defined

- name: Add Duplicati Web Interface (If Configured)
  set_fact:
    duplicati_execstart_cmd: '{{ duplicati_execstart_cmd + ' ' + duplicati_webservice_interface }}'
  when: duplicati_web_interface is defined

- name: Add Duplicati Web Allowed Hostnames (If Configured)
  set_fact:
    duplicati_execstart_cmd: '{{ duplicati_execstart_cmd + ' ' + duplicati_webservice_allowed_hostnames }}'
  when: duplicati_web_hostnames is defined
