---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Gathering Facts
      become: false
      setup:
        gather_subset:
          - '!all'
          - network
          - hardware
    - name: Ensure Required Packages Are Present
      become: true
      apt:
        name: '{{ item }}'
      loop:
        - xz-utils
      when: ansible_os_family | lower == 'debian'
  roles:
    - role: hwwilliams.duplicati
